// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApBaseInfo.proto

package com.qianli.ilink.cloud_platform.messagecenter.pojo.dto;

public final class ApBaseInfoProto {
  private ApBaseInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApBaseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApBaseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ap_mac = 1;</code>
     */
    java.lang.String getApMac();
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    com.google.protobuf.ByteString
        getApMacBytes();

    /**
     * <code>optional string ap_wanip = 2;</code>
     */
    java.lang.String getApWanip();
    /**
     * <code>optional string ap_wanip = 2;</code>
     */
    com.google.protobuf.ByteString
        getApWanipBytes();

    /**
     * <code>optional string ap_model = 3;</code>
     */
    java.lang.String getApModel();
    /**
     * <code>optional string ap_model = 3;</code>
     */
    com.google.protobuf.ByteString
        getApModelBytes();

    /**
     * <code>optional int32 status = 4;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code ApBaseInfo}
   */
  public  static final class ApBaseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApBaseInfo)
      ApBaseInfoOrBuilder {
    // Use ApBaseInfo.newBuilder() to construct.
    private ApBaseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApBaseInfo() {
      apMac_ = "";
      apWanip_ = "";
      apModel_ = "";
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApBaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              apMac_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              apWanip_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              apModel_ = s;
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.internal_static_ApBaseInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.internal_static_ApBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.Builder.class);
    }

    public static final int AP_MAC_FIELD_NUMBER = 1;
    private volatile java.lang.Object apMac_;
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public java.lang.String getApMac() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApMacBytes() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AP_WANIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object apWanip_;
    /**
     * <code>optional string ap_wanip = 2;</code>
     */
    public java.lang.String getApWanip() {
      java.lang.Object ref = apWanip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apWanip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_wanip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getApWanipBytes() {
      java.lang.Object ref = apWanip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apWanip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AP_MODEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object apModel_;
    /**
     * <code>optional string ap_model = 3;</code>
     */
    public java.lang.String getApModel() {
      java.lang.Object ref = apModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apModel_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_model = 3;</code>
     */
    public com.google.protobuf.ByteString
        getApModelBytes() {
      java.lang.Object ref = apModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional int32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apMac_);
      }
      if (!getApWanipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, apWanip_);
      }
      if (!getApModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, apModel_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apMac_);
      }
      if (!getApWanipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, apWanip_);
      }
      if (!getApModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, apModel_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo) obj;

      boolean result = true;
      result = result && getApMac()
          .equals(other.getApMac());
      result = result && getApWanip()
          .equals(other.getApWanip());
      result = result && getApModel()
          .equals(other.getApModel());
      result = result && (getStatus()
          == other.getStatus());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AP_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getApMac().hashCode();
      hash = (37 * hash) + AP_WANIP_FIELD_NUMBER;
      hash = (53 * hash) + getApWanip().hashCode();
      hash = (37 * hash) + AP_MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getApModel().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApBaseInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.internal_static_ApBaseInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.internal_static_ApBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        apMac_ = "";

        apWanip_ = "";

        apModel_ = "";

        status_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.internal_static_ApBaseInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo(this);
        result.apMac_ = apMac_;
        result.apWanip_ = apWanip_;
        result.apModel_ = apModel_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo.getDefaultInstance()) return this;
        if (!other.getApMac().isEmpty()) {
          apMac_ = other.apMac_;
          onChanged();
        }
        if (!other.getApWanip().isEmpty()) {
          apWanip_ = other.apWanip_;
          onChanged();
        }
        if (!other.getApModel().isEmpty()) {
          apModel_ = other.apModel_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object apMac_ = "";
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public java.lang.String getApMac() {
        java.lang.Object ref = apMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApMacBytes() {
        java.lang.Object ref = apMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder clearApMac() {
        
        apMac_ = getDefaultInstance().getApMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apMac_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apWanip_ = "";
      /**
       * <code>optional string ap_wanip = 2;</code>
       */
      public java.lang.String getApWanip() {
        java.lang.Object ref = apWanip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apWanip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_wanip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getApWanipBytes() {
        java.lang.Object ref = apWanip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apWanip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_wanip = 2;</code>
       */
      public Builder setApWanip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apWanip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_wanip = 2;</code>
       */
      public Builder clearApWanip() {
        
        apWanip_ = getDefaultInstance().getApWanip();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_wanip = 2;</code>
       */
      public Builder setApWanipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apWanip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apModel_ = "";
      /**
       * <code>optional string ap_model = 3;</code>
       */
      public java.lang.String getApModel() {
        java.lang.Object ref = apModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apModel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_model = 3;</code>
       */
      public com.google.protobuf.ByteString
          getApModelBytes() {
        java.lang.Object ref = apModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_model = 3;</code>
       */
      public Builder setApModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_model = 3;</code>
       */
      public Builder clearApModel() {
        
        apModel_ = getDefaultInstance().getApModel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_model = 3;</code>
       */
      public Builder setApModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apModel_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ApBaseInfo)
    }

    // @@protoc_insertion_point(class_scope:ApBaseInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApBaseInfo>
        PARSER = new com.google.protobuf.AbstractParser<ApBaseInfo>() {
      public ApBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApBaseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApBaseInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApBaseInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApBaseInfoProto.ApBaseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApBaseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApBaseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ApBaseInfo.proto\"P\n\nApBaseInfo\022\016\n\006ap_m" +
      "ac\030\001 \001(\t\022\020\n\010ap_wanip\030\002 \001(\t\022\020\n\010ap_model\030\003" +
      " \001(\t\022\016\n\006status\030\004 \001(\005BI\n6com.qianli.ilink" +
      ".cloud_platform.messagecenter.pojo.dtoB\017" +
      "ApBaseInfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApBaseInfo_descriptor,
        new java.lang.String[] { "ApMac", "ApWanip", "ApModel", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
