// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApOfflineStaInfo.proto

package com.qianli.ilink.cloud_platform.messagecenter.pojo.dto;

public final class ApOfflineStaInfoProto {
  private ApOfflineStaInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApOfflineStaInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApOfflineStaInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ap_mac = 1;</code>
     */
    java.lang.String getApMac();
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    com.google.protobuf.ByteString
        getApMacBytes();

    /**
     * <code>optional string sta_mac = 2;</code>
     */
    java.lang.String getStaMac();
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    com.google.protobuf.ByteString
        getStaMacBytes();

    /**
     * <code>optional string bssid_mac = 3;</code>
     */
    java.lang.String getBssidMac();
    /**
     * <code>optional string bssid_mac = 3;</code>
     */
    com.google.protobuf.ByteString
        getBssidMacBytes();
  }
  /**
   * <pre>
   *protoc ./ApOfflineStaInfo.proto --java_out=/Users/kangjuaner/Other_IdeaProjects/cloud_platform/messagecenter/src/main/java
   * </pre>
   *
   * Protobuf type {@code ApOfflineStaInfo}
   */
  public  static final class ApOfflineStaInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApOfflineStaInfo)
      ApOfflineStaInfoOrBuilder {
    // Use ApOfflineStaInfo.newBuilder() to construct.
    private ApOfflineStaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApOfflineStaInfo() {
      apMac_ = "";
      staMac_ = "";
      bssidMac_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApOfflineStaInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              apMac_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              staMac_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bssidMac_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_ApOfflineStaInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_ApOfflineStaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder.class);
    }

    public static final int AP_MAC_FIELD_NUMBER = 1;
    private volatile java.lang.Object apMac_;
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public java.lang.String getApMac() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApMacBytes() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STA_MAC_FIELD_NUMBER = 2;
    private volatile java.lang.Object staMac_;
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    public java.lang.String getStaMac() {
      java.lang.Object ref = staMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStaMacBytes() {
      java.lang.Object ref = staMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BSSID_MAC_FIELD_NUMBER = 3;
    private volatile java.lang.Object bssidMac_;
    /**
     * <code>optional string bssid_mac = 3;</code>
     */
    public java.lang.String getBssidMac() {
      java.lang.Object ref = bssidMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bssidMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string bssid_mac = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBssidMacBytes() {
      java.lang.Object ref = bssidMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bssidMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apMac_);
      }
      if (!getStaMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, staMac_);
      }
      if (!getBssidMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bssidMac_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apMac_);
      }
      if (!getStaMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, staMac_);
      }
      if (!getBssidMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bssidMac_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo) obj;

      boolean result = true;
      result = result && getApMac()
          .equals(other.getApMac());
      result = result && getStaMac()
          .equals(other.getStaMac());
      result = result && getBssidMac()
          .equals(other.getBssidMac());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AP_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getApMac().hashCode();
      hash = (37 * hash) + STA_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getStaMac().hashCode();
      hash = (37 * hash) + BSSID_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getBssidMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protoc ./ApOfflineStaInfo.proto --java_out=/Users/kangjuaner/Other_IdeaProjects/cloud_platform/messagecenter/src/main/java
     * </pre>
     *
     * Protobuf type {@code ApOfflineStaInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApOfflineStaInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_ApOfflineStaInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_ApOfflineStaInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        apMac_ = "";

        staMac_ = "";

        bssidMac_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_ApOfflineStaInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo(this);
        result.apMac_ = apMac_;
        result.staMac_ = staMac_;
        result.bssidMac_ = bssidMac_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.getDefaultInstance()) return this;
        if (!other.getApMac().isEmpty()) {
          apMac_ = other.apMac_;
          onChanged();
        }
        if (!other.getStaMac().isEmpty()) {
          staMac_ = other.staMac_;
          onChanged();
        }
        if (!other.getBssidMac().isEmpty()) {
          bssidMac_ = other.bssidMac_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object apMac_ = "";
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public java.lang.String getApMac() {
        java.lang.Object ref = apMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApMacBytes() {
        java.lang.Object ref = apMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder clearApMac() {
        
        apMac_ = getDefaultInstance().getApMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apMac_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object staMac_ = "";
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public java.lang.String getStaMac() {
        java.lang.Object ref = staMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          staMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStaMacBytes() {
        java.lang.Object ref = staMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder setStaMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        staMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder clearStaMac() {
        
        staMac_ = getDefaultInstance().getStaMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder setStaMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        staMac_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bssidMac_ = "";
      /**
       * <code>optional string bssid_mac = 3;</code>
       */
      public java.lang.String getBssidMac() {
        java.lang.Object ref = bssidMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bssidMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bssid_mac = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBssidMacBytes() {
        java.lang.Object ref = bssidMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bssidMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bssid_mac = 3;</code>
       */
      public Builder setBssidMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bssidMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bssid_mac = 3;</code>
       */
      public Builder clearBssidMac() {
        
        bssidMac_ = getDefaultInstance().getBssidMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bssid_mac = 3;</code>
       */
      public Builder setBssidMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bssidMac_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ApOfflineStaInfo)
    }

    // @@protoc_insertion_point(class_scope:ApOfflineStaInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApOfflineStaInfo>
        PARSER = new com.google.protobuf.AbstractParser<ApOfflineStaInfo>() {
      public ApOfflineStaInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApOfflineStaInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApOfflineStaInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApOfflineStaInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TotalApOfflineStaInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TotalApOfflineStaInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 total = 1;</code>
     */
    int getTotal();

    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> 
        getOfflineStaList();
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getOfflineSta(int index);
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    int getOfflineStaCount();
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder> 
        getOfflineStaOrBuilderList();
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder getOfflineStaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TotalApOfflineStaInfo}
   */
  public  static final class TotalApOfflineStaInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TotalApOfflineStaInfo)
      TotalApOfflineStaInfoOrBuilder {
    // Use TotalApOfflineStaInfo.newBuilder() to construct.
    private TotalApOfflineStaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TotalApOfflineStaInfo() {
      total_ = 0;
      offlineSta_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TotalApOfflineStaInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              total_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                offlineSta_ = new java.util.ArrayList<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              offlineSta_.add(
                  input.readMessage(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          offlineSta_ = java.util.Collections.unmodifiableList(offlineSta_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_TotalApOfflineStaInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_TotalApOfflineStaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.Builder.class);
    }

    private int bitField0_;
    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    /**
     * <code>optional int32 total = 1;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int OFFLINE_STA_FIELD_NUMBER = 2;
    private java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> offlineSta_;
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> getOfflineStaList() {
      return offlineSta_;
    }
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    public java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder> 
        getOfflineStaOrBuilderList() {
      return offlineSta_;
    }
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    public int getOfflineStaCount() {
      return offlineSta_.size();
    }
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getOfflineSta(int index) {
      return offlineSta_.get(index);
    }
    /**
     * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
     */
    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder getOfflineStaOrBuilder(
        int index) {
      return offlineSta_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (total_ != 0) {
        output.writeInt32(1, total_);
      }
      for (int i = 0; i < offlineSta_.size(); i++) {
        output.writeMessage(2, offlineSta_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (total_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, total_);
      }
      for (int i = 0; i < offlineSta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, offlineSta_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo) obj;

      boolean result = true;
      result = result && (getTotal()
          == other.getTotal());
      result = result && getOfflineStaList()
          .equals(other.getOfflineStaList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal();
      if (getOfflineStaCount() > 0) {
        hash = (37 * hash) + OFFLINE_STA_FIELD_NUMBER;
        hash = (53 * hash) + getOfflineStaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TotalApOfflineStaInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TotalApOfflineStaInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_TotalApOfflineStaInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_TotalApOfflineStaInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOfflineStaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        total_ = 0;

        if (offlineStaBuilder_ == null) {
          offlineSta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          offlineStaBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.internal_static_TotalApOfflineStaInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.total_ = total_;
        if (offlineStaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            offlineSta_ = java.util.Collections.unmodifiableList(offlineSta_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.offlineSta_ = offlineSta_;
        } else {
          result.offlineSta_ = offlineStaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo.getDefaultInstance()) return this;
        if (other.getTotal() != 0) {
          setTotal(other.getTotal());
        }
        if (offlineStaBuilder_ == null) {
          if (!other.offlineSta_.isEmpty()) {
            if (offlineSta_.isEmpty()) {
              offlineSta_ = other.offlineSta_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOfflineStaIsMutable();
              offlineSta_.addAll(other.offlineSta_);
            }
            onChanged();
          }
        } else {
          if (!other.offlineSta_.isEmpty()) {
            if (offlineStaBuilder_.isEmpty()) {
              offlineStaBuilder_.dispose();
              offlineStaBuilder_ = null;
              offlineSta_ = other.offlineSta_;
              bitField0_ = (bitField0_ & ~0x00000002);
              offlineStaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOfflineStaFieldBuilder() : null;
            } else {
              offlineStaBuilder_.addAllMessages(other.offlineSta_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int total_ ;
      /**
       * <code>optional int32 total = 1;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>optional int32 total = 1;</code>
       */
      public Builder setTotal(int value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 total = 1;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> offlineSta_ =
        java.util.Collections.emptyList();
      private void ensureOfflineStaIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          offlineSta_ = new java.util.ArrayList<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo>(offlineSta_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder> offlineStaBuilder_;

      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> getOfflineStaList() {
        if (offlineStaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(offlineSta_);
        } else {
          return offlineStaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public int getOfflineStaCount() {
        if (offlineStaBuilder_ == null) {
          return offlineSta_.size();
        } else {
          return offlineStaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo getOfflineSta(int index) {
        if (offlineStaBuilder_ == null) {
          return offlineSta_.get(index);
        } else {
          return offlineStaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder setOfflineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo value) {
        if (offlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOfflineStaIsMutable();
          offlineSta_.set(index, value);
          onChanged();
        } else {
          offlineStaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder setOfflineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder builderForValue) {
        if (offlineStaBuilder_ == null) {
          ensureOfflineStaIsMutable();
          offlineSta_.set(index, builderForValue.build());
          onChanged();
        } else {
          offlineStaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder addOfflineSta(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo value) {
        if (offlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOfflineStaIsMutable();
          offlineSta_.add(value);
          onChanged();
        } else {
          offlineStaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder addOfflineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo value) {
        if (offlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOfflineStaIsMutable();
          offlineSta_.add(index, value);
          onChanged();
        } else {
          offlineStaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder addOfflineSta(
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder builderForValue) {
        if (offlineStaBuilder_ == null) {
          ensureOfflineStaIsMutable();
          offlineSta_.add(builderForValue.build());
          onChanged();
        } else {
          offlineStaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder addOfflineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder builderForValue) {
        if (offlineStaBuilder_ == null) {
          ensureOfflineStaIsMutable();
          offlineSta_.add(index, builderForValue.build());
          onChanged();
        } else {
          offlineStaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder addAllOfflineSta(
          java.lang.Iterable<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo> values) {
        if (offlineStaBuilder_ == null) {
          ensureOfflineStaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, offlineSta_);
          onChanged();
        } else {
          offlineStaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder clearOfflineSta() {
        if (offlineStaBuilder_ == null) {
          offlineSta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          offlineStaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public Builder removeOfflineSta(int index) {
        if (offlineStaBuilder_ == null) {
          ensureOfflineStaIsMutable();
          offlineSta_.remove(index);
          onChanged();
        } else {
          offlineStaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder getOfflineStaBuilder(
          int index) {
        return getOfflineStaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder getOfflineStaOrBuilder(
          int index) {
        if (offlineStaBuilder_ == null) {
          return offlineSta_.get(index);  } else {
          return offlineStaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder> 
           getOfflineStaOrBuilderList() {
        if (offlineStaBuilder_ != null) {
          return offlineStaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(offlineSta_);
        }
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder addOfflineStaBuilder() {
        return getOfflineStaFieldBuilder().addBuilder(
            com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder addOfflineStaBuilder(
          int index) {
        return getOfflineStaFieldBuilder().addBuilder(
            index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ApOfflineStaInfo offline_sta = 2;</code>
       */
      public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder> 
           getOfflineStaBuilderList() {
        return getOfflineStaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder> 
          getOfflineStaFieldBuilder() {
        if (offlineStaBuilder_ == null) {
          offlineStaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.ApOfflineStaInfoOrBuilder>(
                  offlineSta_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          offlineSta_ = null;
        }
        return offlineStaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TotalApOfflineStaInfo)
    }

    // @@protoc_insertion_point(class_scope:TotalApOfflineStaInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TotalApOfflineStaInfo>
        PARSER = new com.google.protobuf.AbstractParser<TotalApOfflineStaInfo>() {
      public TotalApOfflineStaInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TotalApOfflineStaInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TotalApOfflineStaInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TotalApOfflineStaInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOfflineStaInfoProto.TotalApOfflineStaInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApOfflineStaInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApOfflineStaInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TotalApOfflineStaInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TotalApOfflineStaInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ApOfflineStaInfo.proto\"F\n\020ApOfflineSta" +
      "Info\022\016\n\006ap_mac\030\001 \001(\t\022\017\n\007sta_mac\030\002 \001(\t\022\021\n" +
      "\tbssid_mac\030\003 \001(\t\"N\n\025TotalApOfflineStaInf" +
      "o\022\r\n\005total\030\001 \001(\005\022&\n\013offline_sta\030\002 \003(\0132\021." +
      "ApOfflineStaInfoBO\n6com.qianli.ilink.clo" +
      "ud_platform.messagecenter.pojo.dtoB\025ApOf" +
      "flineStaInfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApOfflineStaInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApOfflineStaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApOfflineStaInfo_descriptor,
        new java.lang.String[] { "ApMac", "StaMac", "BssidMac", });
    internal_static_TotalApOfflineStaInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TotalApOfflineStaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TotalApOfflineStaInfo_descriptor,
        new java.lang.String[] { "Total", "OfflineSta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
