// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApOnlineStaInfo.proto

package com.qianli.ilink.cloud_platform.messagecenter.pojo.dto;

public final class ApOnlineStaInfoProto {
  private ApOnlineStaInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApOnlineStaInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApOnlineStaInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ap_mac = 1;</code>
     */
    java.lang.String getApMac();
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    com.google.protobuf.ByteString
        getApMacBytes();

    /**
     * <code>optional string sta_mac = 2;</code>
     */
    java.lang.String getStaMac();
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    com.google.protobuf.ByteString
        getStaMacBytes();

    /**
     * <code>optional string sta_ip = 3;</code>
     */
    java.lang.String getStaIp();
    /**
     * <code>optional string sta_ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getStaIpBytes();

    /**
     * <code>optional bytes ssid = 4;</code>
     */
    com.google.protobuf.ByteString getSsid();

    /**
     * <code>optional int32 signal = 5;</code>
     */
    int getSignal();

    /**
     * <code>optional int32 error_rate = 6;</code>
     */
    int getErrorRate();

    /**
     * <code>optional string bssid_mac = 7;</code>
     */
    java.lang.String getBssidMac();
    /**
     * <code>optional string bssid_mac = 7;</code>
     */
    com.google.protobuf.ByteString
        getBssidMacBytes();
  }
  /**
   * <pre>
   *protoc ./ApOnlineStaInfo.proto --java_out=/Users/kangjuaner/Other_IdeaProjects/cloud_platform/messagecenter/src/main/java
   * </pre>
   *
   * Protobuf type {@code ApOnlineStaInfo}
   */
  public  static final class ApOnlineStaInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApOnlineStaInfo)
      ApOnlineStaInfoOrBuilder {
    // Use ApOnlineStaInfo.newBuilder() to construct.
    private ApOnlineStaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApOnlineStaInfo() {
      apMac_ = "";
      staMac_ = "";
      staIp_ = "";
      ssid_ = com.google.protobuf.ByteString.EMPTY;
      signal_ = 0;
      errorRate_ = 0;
      bssidMac_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApOnlineStaInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              apMac_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              staMac_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              staIp_ = s;
              break;
            }
            case 34: {

              ssid_ = input.readBytes();
              break;
            }
            case 40: {

              signal_ = input.readInt32();
              break;
            }
            case 48: {

              errorRate_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              bssidMac_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_ApOnlineStaInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_ApOnlineStaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder.class);
    }

    public static final int AP_MAC_FIELD_NUMBER = 1;
    private volatile java.lang.Object apMac_;
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public java.lang.String getApMac() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApMacBytes() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STA_MAC_FIELD_NUMBER = 2;
    private volatile java.lang.Object staMac_;
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    public java.lang.String getStaMac() {
      java.lang.Object ref = staMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sta_mac = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStaMacBytes() {
      java.lang.Object ref = staMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STA_IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object staIp_;
    /**
     * <code>optional string sta_ip = 3;</code>
     */
    public java.lang.String getStaIp() {
      java.lang.Object ref = staIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staIp_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sta_ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStaIpBytes() {
      java.lang.Object ref = staIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SSID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString ssid_;
    /**
     * <code>optional bytes ssid = 4;</code>
     */
    public com.google.protobuf.ByteString getSsid() {
      return ssid_;
    }

    public static final int SIGNAL_FIELD_NUMBER = 5;
    private int signal_;
    /**
     * <code>optional int32 signal = 5;</code>
     */
    public int getSignal() {
      return signal_;
    }

    public static final int ERROR_RATE_FIELD_NUMBER = 6;
    private int errorRate_;
    /**
     * <code>optional int32 error_rate = 6;</code>
     */
    public int getErrorRate() {
      return errorRate_;
    }

    public static final int BSSID_MAC_FIELD_NUMBER = 7;
    private volatile java.lang.Object bssidMac_;
    /**
     * <code>optional string bssid_mac = 7;</code>
     */
    public java.lang.String getBssidMac() {
      java.lang.Object ref = bssidMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bssidMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string bssid_mac = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBssidMacBytes() {
      java.lang.Object ref = bssidMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bssidMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apMac_);
      }
      if (!getStaMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, staMac_);
      }
      if (!getStaIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, staIp_);
      }
      if (!ssid_.isEmpty()) {
        output.writeBytes(4, ssid_);
      }
      if (signal_ != 0) {
        output.writeInt32(5, signal_);
      }
      if (errorRate_ != 0) {
        output.writeInt32(6, errorRate_);
      }
      if (!getBssidMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, bssidMac_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apMac_);
      }
      if (!getStaMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, staMac_);
      }
      if (!getStaIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, staIp_);
      }
      if (!ssid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, ssid_);
      }
      if (signal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, signal_);
      }
      if (errorRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, errorRate_);
      }
      if (!getBssidMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, bssidMac_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo) obj;

      boolean result = true;
      result = result && getApMac()
          .equals(other.getApMac());
      result = result && getStaMac()
          .equals(other.getStaMac());
      result = result && getStaIp()
          .equals(other.getStaIp());
      result = result && getSsid()
          .equals(other.getSsid());
      result = result && (getSignal()
          == other.getSignal());
      result = result && (getErrorRate()
          == other.getErrorRate());
      result = result && getBssidMac()
          .equals(other.getBssidMac());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AP_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getApMac().hashCode();
      hash = (37 * hash) + STA_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getStaMac().hashCode();
      hash = (37 * hash) + STA_IP_FIELD_NUMBER;
      hash = (53 * hash) + getStaIp().hashCode();
      hash = (37 * hash) + SSID_FIELD_NUMBER;
      hash = (53 * hash) + getSsid().hashCode();
      hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
      hash = (53 * hash) + getSignal();
      hash = (37 * hash) + ERROR_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorRate();
      hash = (37 * hash) + BSSID_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getBssidMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protoc ./ApOnlineStaInfo.proto --java_out=/Users/kangjuaner/Other_IdeaProjects/cloud_platform/messagecenter/src/main/java
     * </pre>
     *
     * Protobuf type {@code ApOnlineStaInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApOnlineStaInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_ApOnlineStaInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_ApOnlineStaInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        apMac_ = "";

        staMac_ = "";

        staIp_ = "";

        ssid_ = com.google.protobuf.ByteString.EMPTY;

        signal_ = 0;

        errorRate_ = 0;

        bssidMac_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_ApOnlineStaInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo(this);
        result.apMac_ = apMac_;
        result.staMac_ = staMac_;
        result.staIp_ = staIp_;
        result.ssid_ = ssid_;
        result.signal_ = signal_;
        result.errorRate_ = errorRate_;
        result.bssidMac_ = bssidMac_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.getDefaultInstance()) return this;
        if (!other.getApMac().isEmpty()) {
          apMac_ = other.apMac_;
          onChanged();
        }
        if (!other.getStaMac().isEmpty()) {
          staMac_ = other.staMac_;
          onChanged();
        }
        if (!other.getStaIp().isEmpty()) {
          staIp_ = other.staIp_;
          onChanged();
        }
        if (other.getSsid() != com.google.protobuf.ByteString.EMPTY) {
          setSsid(other.getSsid());
        }
        if (other.getSignal() != 0) {
          setSignal(other.getSignal());
        }
        if (other.getErrorRate() != 0) {
          setErrorRate(other.getErrorRate());
        }
        if (!other.getBssidMac().isEmpty()) {
          bssidMac_ = other.bssidMac_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object apMac_ = "";
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public java.lang.String getApMac() {
        java.lang.Object ref = apMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApMacBytes() {
        java.lang.Object ref = apMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder clearApMac() {
        
        apMac_ = getDefaultInstance().getApMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apMac_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object staMac_ = "";
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public java.lang.String getStaMac() {
        java.lang.Object ref = staMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          staMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStaMacBytes() {
        java.lang.Object ref = staMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder setStaMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        staMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder clearStaMac() {
        
        staMac_ = getDefaultInstance().getStaMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_mac = 2;</code>
       */
      public Builder setStaMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        staMac_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object staIp_ = "";
      /**
       * <code>optional string sta_ip = 3;</code>
       */
      public java.lang.String getStaIp() {
        java.lang.Object ref = staIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          staIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sta_ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStaIpBytes() {
        java.lang.Object ref = staIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sta_ip = 3;</code>
       */
      public Builder setStaIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        staIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_ip = 3;</code>
       */
      public Builder clearStaIp() {
        
        staIp_ = getDefaultInstance().getStaIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sta_ip = 3;</code>
       */
      public Builder setStaIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        staIp_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString ssid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ssid = 4;</code>
       */
      public com.google.protobuf.ByteString getSsid() {
        return ssid_;
      }
      /**
       * <code>optional bytes ssid = 4;</code>
       */
      public Builder setSsid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ssid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ssid = 4;</code>
       */
      public Builder clearSsid() {
        
        ssid_ = getDefaultInstance().getSsid();
        onChanged();
        return this;
      }

      private int signal_ ;
      /**
       * <code>optional int32 signal = 5;</code>
       */
      public int getSignal() {
        return signal_;
      }
      /**
       * <code>optional int32 signal = 5;</code>
       */
      public Builder setSignal(int value) {
        
        signal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 signal = 5;</code>
       */
      public Builder clearSignal() {
        
        signal_ = 0;
        onChanged();
        return this;
      }

      private int errorRate_ ;
      /**
       * <code>optional int32 error_rate = 6;</code>
       */
      public int getErrorRate() {
        return errorRate_;
      }
      /**
       * <code>optional int32 error_rate = 6;</code>
       */
      public Builder setErrorRate(int value) {
        
        errorRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 error_rate = 6;</code>
       */
      public Builder clearErrorRate() {
        
        errorRate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bssidMac_ = "";
      /**
       * <code>optional string bssid_mac = 7;</code>
       */
      public java.lang.String getBssidMac() {
        java.lang.Object ref = bssidMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bssidMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bssid_mac = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBssidMacBytes() {
        java.lang.Object ref = bssidMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bssidMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bssid_mac = 7;</code>
       */
      public Builder setBssidMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bssidMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bssid_mac = 7;</code>
       */
      public Builder clearBssidMac() {
        
        bssidMac_ = getDefaultInstance().getBssidMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bssid_mac = 7;</code>
       */
      public Builder setBssidMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bssidMac_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ApOnlineStaInfo)
    }

    // @@protoc_insertion_point(class_scope:ApOnlineStaInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApOnlineStaInfo>
        PARSER = new com.google.protobuf.AbstractParser<ApOnlineStaInfo>() {
      public ApOnlineStaInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApOnlineStaInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApOnlineStaInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApOnlineStaInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TotalApOnlineStaInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TotalApOnlineStaInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 total = 1;</code>
     */
    int getTotal();

    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> 
        getOnlineStaList();
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getOnlineSta(int index);
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    int getOnlineStaCount();
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder> 
        getOnlineStaOrBuilderList();
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder getOnlineStaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TotalApOnlineStaInfo}
   */
  public  static final class TotalApOnlineStaInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TotalApOnlineStaInfo)
      TotalApOnlineStaInfoOrBuilder {
    // Use TotalApOnlineStaInfo.newBuilder() to construct.
    private TotalApOnlineStaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TotalApOnlineStaInfo() {
      total_ = 0;
      onlineSta_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TotalApOnlineStaInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              total_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                onlineSta_ = new java.util.ArrayList<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              onlineSta_.add(
                  input.readMessage(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          onlineSta_ = java.util.Collections.unmodifiableList(onlineSta_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_TotalApOnlineStaInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_TotalApOnlineStaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.Builder.class);
    }

    private int bitField0_;
    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    /**
     * <code>optional int32 total = 1;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int ONLINE_STA_FIELD_NUMBER = 2;
    private java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> onlineSta_;
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> getOnlineStaList() {
      return onlineSta_;
    }
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    public java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder> 
        getOnlineStaOrBuilderList() {
      return onlineSta_;
    }
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    public int getOnlineStaCount() {
      return onlineSta_.size();
    }
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getOnlineSta(int index) {
      return onlineSta_.get(index);
    }
    /**
     * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
     */
    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder getOnlineStaOrBuilder(
        int index) {
      return onlineSta_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (total_ != 0) {
        output.writeInt32(1, total_);
      }
      for (int i = 0; i < onlineSta_.size(); i++) {
        output.writeMessage(2, onlineSta_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (total_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, total_);
      }
      for (int i = 0; i < onlineSta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, onlineSta_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo) obj;

      boolean result = true;
      result = result && (getTotal()
          == other.getTotal());
      result = result && getOnlineStaList()
          .equals(other.getOnlineStaList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal();
      if (getOnlineStaCount() > 0) {
        hash = (37 * hash) + ONLINE_STA_FIELD_NUMBER;
        hash = (53 * hash) + getOnlineStaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TotalApOnlineStaInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TotalApOnlineStaInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_TotalApOnlineStaInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_TotalApOnlineStaInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOnlineStaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        total_ = 0;

        if (onlineStaBuilder_ == null) {
          onlineSta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          onlineStaBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.internal_static_TotalApOnlineStaInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.total_ = total_;
        if (onlineStaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            onlineSta_ = java.util.Collections.unmodifiableList(onlineSta_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.onlineSta_ = onlineSta_;
        } else {
          result.onlineSta_ = onlineStaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo.getDefaultInstance()) return this;
        if (other.getTotal() != 0) {
          setTotal(other.getTotal());
        }
        if (onlineStaBuilder_ == null) {
          if (!other.onlineSta_.isEmpty()) {
            if (onlineSta_.isEmpty()) {
              onlineSta_ = other.onlineSta_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOnlineStaIsMutable();
              onlineSta_.addAll(other.onlineSta_);
            }
            onChanged();
          }
        } else {
          if (!other.onlineSta_.isEmpty()) {
            if (onlineStaBuilder_.isEmpty()) {
              onlineStaBuilder_.dispose();
              onlineStaBuilder_ = null;
              onlineSta_ = other.onlineSta_;
              bitField0_ = (bitField0_ & ~0x00000002);
              onlineStaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOnlineStaFieldBuilder() : null;
            } else {
              onlineStaBuilder_.addAllMessages(other.onlineSta_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int total_ ;
      /**
       * <code>optional int32 total = 1;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>optional int32 total = 1;</code>
       */
      public Builder setTotal(int value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 total = 1;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> onlineSta_ =
        java.util.Collections.emptyList();
      private void ensureOnlineStaIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          onlineSta_ = new java.util.ArrayList<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo>(onlineSta_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder> onlineStaBuilder_;

      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> getOnlineStaList() {
        if (onlineStaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(onlineSta_);
        } else {
          return onlineStaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public int getOnlineStaCount() {
        if (onlineStaBuilder_ == null) {
          return onlineSta_.size();
        } else {
          return onlineStaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo getOnlineSta(int index) {
        if (onlineStaBuilder_ == null) {
          return onlineSta_.get(index);
        } else {
          return onlineStaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder setOnlineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo value) {
        if (onlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnlineStaIsMutable();
          onlineSta_.set(index, value);
          onChanged();
        } else {
          onlineStaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder setOnlineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder builderForValue) {
        if (onlineStaBuilder_ == null) {
          ensureOnlineStaIsMutable();
          onlineSta_.set(index, builderForValue.build());
          onChanged();
        } else {
          onlineStaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder addOnlineSta(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo value) {
        if (onlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnlineStaIsMutable();
          onlineSta_.add(value);
          onChanged();
        } else {
          onlineStaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder addOnlineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo value) {
        if (onlineStaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnlineStaIsMutable();
          onlineSta_.add(index, value);
          onChanged();
        } else {
          onlineStaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder addOnlineSta(
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder builderForValue) {
        if (onlineStaBuilder_ == null) {
          ensureOnlineStaIsMutable();
          onlineSta_.add(builderForValue.build());
          onChanged();
        } else {
          onlineStaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder addOnlineSta(
          int index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder builderForValue) {
        if (onlineStaBuilder_ == null) {
          ensureOnlineStaIsMutable();
          onlineSta_.add(index, builderForValue.build());
          onChanged();
        } else {
          onlineStaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder addAllOnlineSta(
          java.lang.Iterable<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo> values) {
        if (onlineStaBuilder_ == null) {
          ensureOnlineStaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, onlineSta_);
          onChanged();
        } else {
          onlineStaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder clearOnlineSta() {
        if (onlineStaBuilder_ == null) {
          onlineSta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          onlineStaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public Builder removeOnlineSta(int index) {
        if (onlineStaBuilder_ == null) {
          ensureOnlineStaIsMutable();
          onlineSta_.remove(index);
          onChanged();
        } else {
          onlineStaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder getOnlineStaBuilder(
          int index) {
        return getOnlineStaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder getOnlineStaOrBuilder(
          int index) {
        if (onlineStaBuilder_ == null) {
          return onlineSta_.get(index);  } else {
          return onlineStaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public java.util.List<? extends com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder> 
           getOnlineStaOrBuilderList() {
        if (onlineStaBuilder_ != null) {
          return onlineStaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(onlineSta_);
        }
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder addOnlineStaBuilder() {
        return getOnlineStaFieldBuilder().addBuilder(
            com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder addOnlineStaBuilder(
          int index) {
        return getOnlineStaFieldBuilder().addBuilder(
            index, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ApOnlineStaInfo online_sta = 2;</code>
       */
      public java.util.List<com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder> 
           getOnlineStaBuilderList() {
        return getOnlineStaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder> 
          getOnlineStaFieldBuilder() {
        if (onlineStaBuilder_ == null) {
          onlineStaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfo.Builder, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.ApOnlineStaInfoOrBuilder>(
                  onlineSta_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          onlineSta_ = null;
        }
        return onlineStaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TotalApOnlineStaInfo)
    }

    // @@protoc_insertion_point(class_scope:TotalApOnlineStaInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TotalApOnlineStaInfo>
        PARSER = new com.google.protobuf.AbstractParser<TotalApOnlineStaInfo>() {
      public TotalApOnlineStaInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TotalApOnlineStaInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TotalApOnlineStaInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TotalApOnlineStaInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApOnlineStaInfoProto.TotalApOnlineStaInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApOnlineStaInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApOnlineStaInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TotalApOnlineStaInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TotalApOnlineStaInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ApOnlineStaInfo.proto\"\207\001\n\017ApOnlineStaI" +
      "nfo\022\016\n\006ap_mac\030\001 \001(\t\022\017\n\007sta_mac\030\002 \001(\t\022\016\n\006" +
      "sta_ip\030\003 \001(\t\022\014\n\004ssid\030\004 \001(\014\022\016\n\006signal\030\005 \001" +
      "(\005\022\022\n\nerror_rate\030\006 \001(\005\022\021\n\tbssid_mac\030\007 \001(" +
      "\t\"K\n\024TotalApOnlineStaInfo\022\r\n\005total\030\001 \001(\005" +
      "\022$\n\nonline_sta\030\002 \003(\0132\020.ApOnlineStaInfoBN" +
      "\n6com.qianli.ilink.cloud_platform.messag" +
      "ecenter.pojo.dtoB\024ApOnlineStaInfoProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApOnlineStaInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApOnlineStaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApOnlineStaInfo_descriptor,
        new java.lang.String[] { "ApMac", "StaMac", "StaIp", "Ssid", "Signal", "ErrorRate", "BssidMac", });
    internal_static_TotalApOnlineStaInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TotalApOnlineStaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TotalApOnlineStaInfo_descriptor,
        new java.lang.String[] { "Total", "OnlineSta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
