// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApStatusInfo.proto

package com.qianli.ilink.cloud_platform.messagecenter.pojo.dto;

public final class ApStatusInfoProto {
  private ApStatusInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApStatusInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApStatusInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ap_mac = 1;</code>
     */
    java.lang.String getApMac();
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    com.google.protobuf.ByteString
        getApMacBytes();

    /**
     * <code>optional int32 rx_bytes = 2;</code>
     */
    int getRxBytes();

    /**
     * <code>optional int32 tx_bytes = 3;</code>
     */
    int getTxBytes();

    /**
     * <code>optional int32 total_user = 4;</code>
     */
    int getTotalUser();

    /**
     * <code>optional int64 last_timestamp = 5;</code>
     */
    long getLastTimestamp();

    /**
     * <code>optional int64 cur_timestamp = 6;</code>
     */
    long getCurTimestamp();
  }
  /**
   * Protobuf type {@code ApStatusInfo}
   */
  public  static final class ApStatusInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApStatusInfo)
      ApStatusInfoOrBuilder {
    // Use ApStatusInfo.newBuilder() to construct.
    private ApStatusInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApStatusInfo() {
      apMac_ = "";
      rxBytes_ = 0;
      txBytes_ = 0;
      totalUser_ = 0;
      lastTimestamp_ = 0L;
      curTimestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApStatusInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              apMac_ = s;
              break;
            }
            case 16: {

              rxBytes_ = input.readInt32();
              break;
            }
            case 24: {

              txBytes_ = input.readInt32();
              break;
            }
            case 32: {

              totalUser_ = input.readInt32();
              break;
            }
            case 40: {

              lastTimestamp_ = input.readInt64();
              break;
            }
            case 48: {

              curTimestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.internal_static_ApStatusInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.internal_static_ApStatusInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.Builder.class);
    }

    public static final int AP_MAC_FIELD_NUMBER = 1;
    private volatile java.lang.Object apMac_;
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public java.lang.String getApMac() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apMac_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ap_mac = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApMacBytes() {
      java.lang.Object ref = apMac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RX_BYTES_FIELD_NUMBER = 2;
    private int rxBytes_;
    /**
     * <code>optional int32 rx_bytes = 2;</code>
     */
    public int getRxBytes() {
      return rxBytes_;
    }

    public static final int TX_BYTES_FIELD_NUMBER = 3;
    private int txBytes_;
    /**
     * <code>optional int32 tx_bytes = 3;</code>
     */
    public int getTxBytes() {
      return txBytes_;
    }

    public static final int TOTAL_USER_FIELD_NUMBER = 4;
    private int totalUser_;
    /**
     * <code>optional int32 total_user = 4;</code>
     */
    public int getTotalUser() {
      return totalUser_;
    }

    public static final int LAST_TIMESTAMP_FIELD_NUMBER = 5;
    private long lastTimestamp_;
    /**
     * <code>optional int64 last_timestamp = 5;</code>
     */
    public long getLastTimestamp() {
      return lastTimestamp_;
    }

    public static final int CUR_TIMESTAMP_FIELD_NUMBER = 6;
    private long curTimestamp_;
    /**
     * <code>optional int64 cur_timestamp = 6;</code>
     */
    public long getCurTimestamp() {
      return curTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apMac_);
      }
      if (rxBytes_ != 0) {
        output.writeInt32(2, rxBytes_);
      }
      if (txBytes_ != 0) {
        output.writeInt32(3, txBytes_);
      }
      if (totalUser_ != 0) {
        output.writeInt32(4, totalUser_);
      }
      if (lastTimestamp_ != 0L) {
        output.writeInt64(5, lastTimestamp_);
      }
      if (curTimestamp_ != 0L) {
        output.writeInt64(6, curTimestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apMac_);
      }
      if (rxBytes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rxBytes_);
      }
      if (txBytes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, txBytes_);
      }
      if (totalUser_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalUser_);
      }
      if (lastTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lastTimestamp_);
      }
      if (curTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, curTimestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo)) {
        return super.equals(obj);
      }
      com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo other = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo) obj;

      boolean result = true;
      result = result && getApMac()
          .equals(other.getApMac());
      result = result && (getRxBytes()
          == other.getRxBytes());
      result = result && (getTxBytes()
          == other.getTxBytes());
      result = result && (getTotalUser()
          == other.getTotalUser());
      result = result && (getLastTimestamp()
          == other.getLastTimestamp());
      result = result && (getCurTimestamp()
          == other.getCurTimestamp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AP_MAC_FIELD_NUMBER;
      hash = (53 * hash) + getApMac().hashCode();
      hash = (37 * hash) + RX_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getRxBytes();
      hash = (37 * hash) + TX_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getTxBytes();
      hash = (37 * hash) + TOTAL_USER_FIELD_NUMBER;
      hash = (53 * hash) + getTotalUser();
      hash = (37 * hash) + LAST_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastTimestamp());
      hash = (37 * hash) + CUR_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApStatusInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApStatusInfo)
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.internal_static_ApStatusInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.internal_static_ApStatusInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.class, com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.Builder.class);
      }

      // Construct using com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        apMac_ = "";

        rxBytes_ = 0;

        txBytes_ = 0;

        totalUser_ = 0;

        lastTimestamp_ = 0L;

        curTimestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.internal_static_ApStatusInfo_descriptor;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo getDefaultInstanceForType() {
        return com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.getDefaultInstance();
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo build() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo buildPartial() {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo result = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo(this);
        result.apMac_ = apMac_;
        result.rxBytes_ = rxBytes_;
        result.txBytes_ = txBytes_;
        result.totalUser_ = totalUser_;
        result.lastTimestamp_ = lastTimestamp_;
        result.curTimestamp_ = curTimestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo) {
          return mergeFrom((com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo other) {
        if (other == com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo.getDefaultInstance()) return this;
        if (!other.getApMac().isEmpty()) {
          apMac_ = other.apMac_;
          onChanged();
        }
        if (other.getRxBytes() != 0) {
          setRxBytes(other.getRxBytes());
        }
        if (other.getTxBytes() != 0) {
          setTxBytes(other.getTxBytes());
        }
        if (other.getTotalUser() != 0) {
          setTotalUser(other.getTotalUser());
        }
        if (other.getLastTimestamp() != 0L) {
          setLastTimestamp(other.getLastTimestamp());
        }
        if (other.getCurTimestamp() != 0L) {
          setCurTimestamp(other.getCurTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object apMac_ = "";
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public java.lang.String getApMac() {
        java.lang.Object ref = apMac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apMac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApMacBytes() {
        java.lang.Object ref = apMac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apMac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder clearApMac() {
        
        apMac_ = getDefaultInstance().getApMac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ap_mac = 1;</code>
       */
      public Builder setApMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apMac_ = value;
        onChanged();
        return this;
      }

      private int rxBytes_ ;
      /**
       * <code>optional int32 rx_bytes = 2;</code>
       */
      public int getRxBytes() {
        return rxBytes_;
      }
      /**
       * <code>optional int32 rx_bytes = 2;</code>
       */
      public Builder setRxBytes(int value) {
        
        rxBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rx_bytes = 2;</code>
       */
      public Builder clearRxBytes() {
        
        rxBytes_ = 0;
        onChanged();
        return this;
      }

      private int txBytes_ ;
      /**
       * <code>optional int32 tx_bytes = 3;</code>
       */
      public int getTxBytes() {
        return txBytes_;
      }
      /**
       * <code>optional int32 tx_bytes = 3;</code>
       */
      public Builder setTxBytes(int value) {
        
        txBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tx_bytes = 3;</code>
       */
      public Builder clearTxBytes() {
        
        txBytes_ = 0;
        onChanged();
        return this;
      }

      private int totalUser_ ;
      /**
       * <code>optional int32 total_user = 4;</code>
       */
      public int getTotalUser() {
        return totalUser_;
      }
      /**
       * <code>optional int32 total_user = 4;</code>
       */
      public Builder setTotalUser(int value) {
        
        totalUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 total_user = 4;</code>
       */
      public Builder clearTotalUser() {
        
        totalUser_ = 0;
        onChanged();
        return this;
      }

      private long lastTimestamp_ ;
      /**
       * <code>optional int64 last_timestamp = 5;</code>
       */
      public long getLastTimestamp() {
        return lastTimestamp_;
      }
      /**
       * <code>optional int64 last_timestamp = 5;</code>
       */
      public Builder setLastTimestamp(long value) {
        
        lastTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_timestamp = 5;</code>
       */
      public Builder clearLastTimestamp() {
        
        lastTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long curTimestamp_ ;
      /**
       * <code>optional int64 cur_timestamp = 6;</code>
       */
      public long getCurTimestamp() {
        return curTimestamp_;
      }
      /**
       * <code>optional int64 cur_timestamp = 6;</code>
       */
      public Builder setCurTimestamp(long value) {
        
        curTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cur_timestamp = 6;</code>
       */
      public Builder clearCurTimestamp() {
        
        curTimestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ApStatusInfo)
    }

    // @@protoc_insertion_point(class_scope:ApStatusInfo)
    private static final com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo();
    }

    public static com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApStatusInfo>
        PARSER = new com.google.protobuf.AbstractParser<ApStatusInfo>() {
      public ApStatusInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApStatusInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApStatusInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApStatusInfo> getParserForType() {
      return PARSER;
    }

    public com.qianli.ilink.cloud_platform.messagecenter.pojo.dto.ApStatusInfoProto.ApStatusInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApStatusInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApStatusInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ApStatusInfo.proto\"\205\001\n\014ApStatusInfo\022\016\n" +
      "\006ap_mac\030\001 \001(\t\022\020\n\010rx_bytes\030\002 \001(\005\022\020\n\010tx_by" +
      "tes\030\003 \001(\005\022\022\n\ntotal_user\030\004 \001(\005\022\026\n\016last_ti" +
      "mestamp\030\005 \001(\003\022\025\n\rcur_timestamp\030\006 \001(\003BK\n6" +
      "com.qianli.ilink.cloud_platform.messagec" +
      "enter.pojo.dtoB\021ApStatusInfoProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApStatusInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApStatusInfo_descriptor,
        new java.lang.String[] { "ApMac", "RxBytes", "TxBytes", "TotalUser", "LastTimestamp", "CurTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
