cloudPlatform:
  requestTimeOut: 5000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8&useSSL=true
  application:
    name: message
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  data:
    mongodb:
      host: 192.168.10.28
      port: 27017
      database: test
      uri: mongodb://192.168.10.28:27017/test
heartbeat:
  udpServerList: 127.0.0.1:12222,127.0.0.1:13333
  retryTimes: 3
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    hostname: message-center
    prefer-ip-address: true
---
spring:
  profiles: test
server:
  port: 9000
---
spring:
  profiles: dev
server:
  port: 9001