server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /messagecenter
spring:
  application:
    name: messagecenter
async:
  threadpool:
    corePoolSize: ${CORE_POOL_SIZE:20}
    maxPoolSize: ${MAX_POOL_SIZE:500}
    queueCapacity: ${QUEUE_CAPACITY:500}
    keepAliveSeconds: ${KEEPALIVE_SECONDS:60}
kafka:
  messageTopic: ${MESSAGE_TOPIC:messageReceiver}
  bootstrapServers: ${BOOTSTRAP_SERVERS:127.0.0.1:9092}
  batchSize: 16384
  lingerMs: 5000